### ISSUE TITLE
bug: Unknown pgwire::pg_protocol: Error: ReadMsgError: unexpected end of file.

### ISSUE THREAD

**Issue by BowenXiao1999** [singularity-data/risingwave#4376] opened 2022-08-02 10:30 UTC
**Describe the bug**
`2022-08-02T10:26:09.198018Z ERROR pgwire::pg_protocol: Error: ReadMsgError: unexpected end of file.` will appear in log (or console).

**To Reproduce**
1. ./risdev p
2.  ./risedev slt -p 4566 -d dev "./e2e_test/batch/basic/basic.slt.part" (Run e2e test on one file)

**Expected behavior**
The error log should not be shown

**Additional context**

**Comment by BowenXiao1999** [comment] 2022-08-02 10:30
@ZENOTME would you please take a look?

**Comment by ZENOTME** [comment] 2022-08-03 07:06
### What cause this bug
Server will maintain a 'Connection' with 'Client' and close the 'Connection' normally when 'Client' send the 'Terminate' message. 
'./risede slt' will run [tokio-postgres ](https://docs.rs/tokio-postgres/0.7.6/tokio_postgres/) as client and the client in tokio_postgres doesn't send the 'Terminate' when it close automatically. That caused the server still maintain the 'Connection' when the 'Client' has already exits. Finally the server try to read from this invalid 'Connection' and get the UnexpectedEof.
So I think the problem is in tokio-postgres. It should implement the drop trait for client to send 'Terminate' message automatically. The weird thing is it implements a API to send 'Terminate' message but not implementing drop trait.

```
#[doc(hidden)]
pub fn __private_api_close(&mut self) {
      self.inner.sender.close_channel()
}
```

### How we fix it?
Anyway, for now our solution is hide the error log (which is the original solution). Because it's the error from client and we needn't report it. Just closing the connection is enough.

**Closed** 2022-08-03 10:19 UTC
Labels: type/bug
