### ISSUE TITLE
bug: compute node panic on DROP SOURCE

### ISSUE THREAD

**Issue by hzxa21** [singularity-data/risingwave#4870] opened 2022-08-24 17:47 UTC
### Describe the bug

commit id: `1b59d2c247d62e28b11bfd26325b72767751571d`

I created two sources and dropped then one by one. The second DROP SOURCE failed and all compute nodes panic with the following stack trace:

![image](https://user-images.githubusercontent.com/5518566/186487736-fa4b22b6-38f5-4f9b-bc43-41d85ecfbf39.png)

### To Reproduce

![image](https://user-images.githubusercontent.com/5518566/186487968-cc5c3c27-8b03-44c4-9bcb-036366780570.png)

### Expected behavior

DROP SOURCE succeeds without causing CN panic

### Additional context

This may be related to #4442 and #4492

**Comment by hzxa21** [comment] 2022-08-25 02:22
cc @xxhZs Can you take a look?

**Comment by xxhZs** [comment] 2022-08-25 02:30
I think the reason is this pr https://github.com/singularity-data/risingwave/pull/4813

**Comment by fuyufjh** [comment] 2022-08-26 05:58
https://github.com/singularity-data/risingwave/pull/4813 was merged. Could you please help to check whether this has been fixed? @xxhZs

**Comment by xxhZs** [comment] 2022-08-29 02:40
> #4813 was merged. Could you please help to check whether this has been fixed? @xxhZs

I try to do some tests with drop mv/source. It has not been reproduced again

**Closed** 2022-08-29 02:40 UTC
Labels: type/bug
