### ISSUE TITLE
Have we removed column constraints "NOT NULL"？

### ISSUE THREAD

**Issue by huangjw806** [singularity-data/risingwave#4513] opened 2022-08-09 02:38 UTC
**Describe the bug**

Today's benchmark cron failed with the following error:

```
[error] Create source tables error: pq: QueryError: Feature is not yet implemented: column constraints "NOT NULL", No tracking issue yet. Feel free to submit a feature request at https://github.com/singularity-data/risingwave/issues/new?labels=type%2Ffeature&template=feature_request.md.
```

SQL ：
```
CREATE SOURCE supplier (
    s_suppkey INTEGER NOT NULL,
    s_name VARCHAR NOT NULL,
    s_address VARCHAR NOT NULL,
    s_nationkey INTEGER NOT NULL,
    s_phone VARCHAR NOT NULL,
    s_acctbal NUMERIC NOT NULL,
    s_comment VARCHAR NOT NULL)
    with (
    connector='kafka',
    kafka.topic='supplier',
    kafka.brokers='${KAFKA_FRONTEND_ADDR}',
    kafka.consumer.group='supplier_consumer'
    ) row format JSON
```
who removed column constraints "NOT NULL" in the most recent commit？

**Comment by liurenjie1024** [comment] 2022-08-09 02:44
cc @xiangjinwu

**Comment by neverchanje** [comment] 2022-08-09 02:53
This is not a bug, it is intended. We dont support not null for the simplity implementation-wise. Moreover, we assume the input stream is schemaless, which means we never know if a field is not null. So we made a decision to remove it.

**Comment by huangjw806** [comment] 2022-08-09 02:55
OK, I'll remove it in tpch-bench.

**Comment by skyzh** [comment] 2022-08-09 02:56
`not null` is ignored before, but now it seems to be banned. is it an expected change?

**Comment by skyzh** [comment] 2022-08-09 02:56
Okay, that's expected -> https://github.com/singularity-data/risingwave/pull/4487

**Comment by xiangjinwu** [comment] 2022-08-09 03:25
Sorry for the disruption. I will make an announcement in the future for such "fake" breaking changes. Shall we close this issue or maybe move it to tpch-bench repo?

**Comment by skyzh** [comment] 2022-08-09 03:33
fixed by https://github.com/singularity-data/tpch-bench/pull/22

**Closed by skyzh** 2022-08-09 03:33 UTC
