### ISSUE TITLE
bug: wrong return value of array access

### ISSUE THREAD

**Issue by KeXiangWang** [singularity-data/risingwave#4833] opened 2022-08-24 03:58 UTC
**Describe the bug**
Get unexpected output.

**To Reproduce**
To create table and insert values
```
CREATE TABLE bid (
    "price" BIGINT,
    "channel" VARCHAR,
    "url" VARCHAR
);

INSERT INTO bid (
    price,
    channel,
    url
) VALUES
(73134520, 'channel-7568', 'query=1&channel_id=163053568'),
(1940, 'channel-9319', 'query=1&channel_id=433848320'),
(12655, 'channel-5136', 'query=1&channel_id=136839168'), 
(19269, 'channel-5775', 'query=1&channel_id=244842496'), 
(43672280, 'channel-9550', 'query=1&channel_id=1923350528'), 
(28953332, 'channel-5698', 'query=1&channel_id=1114112000');
```
query
```
SELECT
    price, channel,
    (regexp_match(url, '(&|^)channel_id=([^&]*)'))[1]
    AS channel_id
FROM
    bid Order by price;
```

**Expected behavior**
Risingwave's output:
```
  price   |   channel    | channel_id
----------+--------------+------------
     1940 | channel-9319 | 433848320
    12655 | channel-5136 | 136839168
    19269 | channel-5775 | 1923350528
 28953332 | channel-5698 | 136839168
 43672280 | channel-9550 | 1923350528
 73134520 | channel-7568 | 163053568
```

The output for the same input in PostgreSQL
```
1940	channel-9319	433848320
12655	channel-5136	136839168
19269	channel-5775	244842496
28953332	channel-5698	1114112000
43672280	channel-9550	1923350528
73134520	channel-7568	163053568
```
**Additional context**
The problem was found while adding nexmark21 support.
Any help is welcomed.

**Comment by fuyufjh** [comment] 2022-08-24 06:58
For this row:

```
(19269, 'channel-5775', 'query=1&channel_id=244842496'), 
```

Expected:

```
19269	channel-5775	244842496
```

Actual:

```
19269 | channel-5775 | 1923350528
```

**Comment by fuyufjh** [comment] 2022-08-24 06:59
@xxchan Please take a look ❤️

**Comment by xxchan** [comment] 2022-08-24 08:38
The output of the expr is correct, but the output of the project is wrong. Investigating...
<img width="685" alt="image" src="https://user-images.githubusercontent.com/37948597/186371814-dc6a8ad3-747f-46eb-8f4f-cccaf0785cac.png">

**Comment by xxchan** [comment] 2022-08-24 08:45
The result is correct when there's no array access.
```
dev=>  select (regexp_match(url, '(&|^)channel_id=([^&]*)')) from bid;
    ?column?
----------------
 {&,433848320}
 {&,163053568}
 {&,244842496}
 {&,1923350528}
 {&,1114112000}
 {&,136839168}
(6 rows)

dev=>  select (regexp_match(url, '(&|^)channel_id=([^&]*)'))[2] from bid;
  ?column?
------------
 1114112000
 1114112000
 244842496
 244842496
 433848320
 163053568
(6 rows)
```


The problem is from array access:
```
dev=> create table t(x int[]);
CREATE_TABLE
dev=> insert into t values (Array[0,1]),(Array[0,2]),(Array[0,3]), (Array[0,4]),(Array[0,5]);
INSERT 0 5
dev=> select x[2] from t;
 ?column?
----------
        3
        1
        2
        4
        4
(5 rows)
```

**Comment by xxchan** [comment] 2022-08-24 08:49
Should be fixed by https://github.com/singularity-data/risingwave/pull/4831

**Closed** 2022-08-25 08:13 UTC
Labels: type/bug, help wanted
